apiVersion: v1
kind: Namespace
metadata:
  name: bcs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-deployment
  namespace: bcs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bcs-app
  template:
    metadata:
      namespace: bcs
      labels:
        app: bcs-app
    spec:
      containers:
        - name: bcs
          image: cr.yandex/crp50ntveojf77o60dde/bcs:__VERSION__
          imagePullPolicy: Always
          ports:
          - containerPort: 443
            protocol: TCP