apiVersion: v1
kind: Namespace
metadata:
  name: bcs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-deployment
  namespace: bcs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bcs-app
  template:
    metadata:
      namespace: bcs
      labels:
        app: bcs-app
    spec:
      containers:
        - name: bcs
          image: cr.yandex/crp50ntveojf77o60dde/bcs:__VERSION__
          imagePullPolicy: Always
          ports:
          - name: https
            containerPort: 443
            protocol: TCP
          - name: http
            containerPort: 80
            protocol: TCP
---
apiVersion: apps/v1
kind: Service
metadata:
  name: bcs-sys
  namespace: bcs
spec:
  type: NodePort
  selector: 
    app: bcs-app
  ports: 
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP